"""
build_excel.py

Creates the executive_reporting.xlsx workbook with:
  - README sheet
  - KPI_Summary sheet
  - Segment_Analysis sheet
  - Retention_Analysis sheet
  - Reconciliation sheet
"""

import pandas as pd
import numpy as np
import os
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side, numbers
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.chart import BarChart, PieChart, Reference

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PROCESSED_DIR = os.path.join(BASE_DIR, "..", "data", "processed")
REPORTS_DIR = os.path.join(BASE_DIR, "..", "reports")
EXCEL_DIR = os.path.join(BASE_DIR, "..", "excel")
OUTPUT_PATH = os.path.join(EXCEL_DIR, "executive_reporting.xlsx")

os.makedirs(EXCEL_DIR, exist_ok=True)

# Load data
features_df = pd.read_csv(os.path.join(PROCESSED_DIR, "customer_features_vB.csv"))

# ============================================================================
# STYLES
# ============================================================================
HEADER_FONT = Font(bold=True, color="FFFFFF", size=11)
HEADER_FILL = PatternFill(start_color="2E75B6", end_color="2E75B6", fill_type="solid")
SUBHEADER_FILL = PatternFill(start_color="BDD7EE", end_color="BDD7EE", fill_type="solid")
ACCENT_FILL = PatternFill(start_color="E7E6E6", end_color="E7E6E6", fill_type="solid")
GREEN_FILL = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
RED_FILL = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")
YELLOW_FILL = PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid")

THIN_BORDER = Border(
    left=Side(style='thin'), right=Side(style='thin'),
    top=Side(style='thin'), bottom=Side(style='thin')
)

def apply_header(row):
    for cell in row:
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
        cell.border = THIN_BORDER

def apply_border(row):
    for cell in row:
        cell.border = THIN_BORDER

def auto_width(ws):
    for column in ws.columns:
        max_length = 0
        column_letter = column[0].column_letter
        for cell in column:
            try:
                if cell.value:
                    max_length = max(max_length, len(str(cell.value)))
            except:
                pass
        ws.column_dimensions[column_letter].width = min(max_length + 2, 40)

# ============================================================================
# CREATE WORKBOOK
# ============================================================================
wb = Workbook()

# ============================================================================
# SHEET 1: README
# ============================================================================
ws_readme = wb.active
ws_readme.title = "README"

readme_content = [
    ["Client Engagement & Subscription Retention Analytics"],
    ["Executive Reporting Workbook"],
    [],
    ["Purpose:"],
    ["This workbook contains key metrics, segment analysis, retention analysis, and reconciliation tables"],
    ["derived from the Client Engagement & Subscription Retention Analytics project."],
    [],
    ["Data Sources:"],
    ["- Public: IBM Telco Customer Churn dataset (customer demographics, subscription details, churn labels)"],
    ["- Synthetic: Interactions, content usage, event participation, account activity"],
    [],
    ["Tools Used:"],
    ["SQL | Python (Pandas) | Excel | Power BI | Statistics"],
    [],
    ["Key Findings:"],
    ["1. Renewal Rate: 84.6% (5,956 renewed, 1,087 churned)"],
    ["2. Contract Type is the strongest predictor: Two year (98.5%), One year (89.4%), Month-to-month (77.6%)"],
    ["3. Tenure strongly correlates with renewal: 0-12 months (76.4%), 49+ months (97.9%)"],
    ["4. Engagement score is NOT significantly different between renewed and churned (p = 0.62)"],
    ["5. Contract type vs renewal is highly significant (chi-square p < 0.001)"],
    ["6. At-risk clients: 221 (3.1%) with 86.0% renewal rate"],
    [],
    ["Sheets in this workbook:"],
    ["- KPI_Summary: Core business metrics and KPIs"],
    ["- Segment_Analysis: Renewal rates by contract type, tenure, engagement band, and value segment"],
    ["- Retention_Analysis: Detailed retention metrics and comparison"],
    ["- Reconciliation: Data reconciliation and quality checks"],
    [],
    ["Generated by: analyze_and_visualize.py"],
    ["Date: 2024"],
]

for row in readme_content:
    ws_readme.append(row)

ws_readme['A1'].font = Font(bold=True, size=16, color="2E75B6")
ws_readme['A2'].font = Font(bold=True, size=12, color="2E75B6")
ws_readme.column_dimensions['A'].width = 80
auto_width(ws_readme)

# ============================================================================
# SHEET 2: KPI_Summary
# ============================================================================
ws_kpi = wb.create_sheet("KPI_Summary")

# Key metrics
total_customers = len(features_df)
renewed = (features_df['churn'] == 'No').sum()
churned = (features_df['churn'] == 'Yes').sum()
renewal_rate = renewed / total_customers * 100
churn_rate = churned / total_customers * 100
total_revenue = features_df['monthly_charges'].sum()
avg_contract_value = features_df['total_charges'].mean()
avg_engagement = features_df['engagement_score'].mean()

kpi_data = [
    ["Metric", "Value", "Notes"],
    ["Total Customers", total_customers, "All customers in dataset"],
    ["Renewed Customers", renewed, f"{renewal_rate:.1f}% of total"],
    ["Churned Customers", churned, f"{churn_rate:.1f}% of total"],
    ["Renewal Rate", f"{renewal_rate:.1f}%", "Percentage of customers who renewed"],
    ["Churn Rate", f"{churn_rate:.1f}%", "Percentage of customers who churned"],
    ["Total Monthly Revenue", f"${total_revenue:,.2f}", "Sum of all monthly charges"],
    ["Average Contract Value", f"${avg_contract_value:.2f}", "Mean total charges per customer"],
    ["Average Engagement Score", f"{avg_engagement:.3f}", "Mean engagement score (0-1 scale)"],
]

for row in kpi_data:
    ws_kpi.append(row)

# Apply header style
apply_header(ws_kpi[1])

# Style the data rows
for row in ws_kpi.iter_rows(min_row=2, max_row=ws_kpi.max_row):
    apply_border(row)
    for cell in row:
        cell.alignment = Alignment(horizontal='left', vertical='center')

auto_width(ws_kpi)

# ============================================================================
# SHEET 3: Segment_Analysis
# ============================================================================
ws_segment = wb.create_sheet("Segment_Analysis")

# Contract type analysis
contract_data = features_df.groupby('Contract').apply(
    lambda x: pd.Series({
        'Total Customers': len(x),
        'Renewed': (x['churn'] == 'No').sum(),
        'Churned': (x['churn'] == 'Yes').sum(),
        'Renewal Rate (%)': round((x['churn'] == 'No').mean() * 100, 2),
        'Avg Monthly Charges': round(x['monthly_charges'].mean(), 2),
        'Avg Contract Value': round(x['total_charges'].mean(), 2),
        'Avg Engagement Score': round(x['engagement_score'].mean(), 4),
    })
).reset_index()

ws_segment.append(["Renewal Rate by Contract Type"])
ws_segment.append([])
for r in dataframe_to_rows(contract_data, index=False, header=True):
    ws_segment.append(r)

apply_header(ws_segment[3])
for row in ws_segment.iter_rows(min_row=4, max_row=ws_segment.max_row):
    apply_border(row)
    for cell in row:
        cell.alignment = Alignment(horizontal='left', vertical='center')

# Tenure band analysis
ws_segment.append([])
ws_segment.append(["Renewal Rate by Tenure Band"])
ws_segment.append([])

tenure_data = features_df.groupby('tenure_band').apply(
    lambda x: pd.Series({
        'Total Customers': len(x),
        'Renewed': (x['churn'] == 'No').sum(),
        'Churned': (x['churn'] == 'Yes').sum(),
        'Renewal Rate (%)': round((x['churn'] == 'No').mean() * 100, 2),
        'Avg Monthly Charges': round(x['monthly_charges'].mean(), 2),
        'Avg Contract Value': round(x['total_charges'].mean(), 2),
        'Avg Engagement Score': round(x['engagement_score'].mean(), 4),
    })
).reindex(['0-12 months', '13-24 months', '25-48 months', '49+ months']).reset_index()

for r in dataframe_to_rows(tenure_data, index=False, header=True):
    ws_segment.append(r)

header_row = ws_segment.max_row - len(tenure_data)
apply_header(ws_segment[header_row])
for row in ws_segment.iter_rows(min_row=header_row + 1, max_row=ws_segment.max_row):
    apply_border(row)
    for cell in row:
        cell.alignment = Alignment(horizontal='left', vertical='center')

auto_width(ws_segment)

# ============================================================================
# SHEET 4: Retention_Analysis
# ============================================================================
ws_retention = wb.create_sheet("Retention_Analysis")

# Renewed vs Non-Renewed comparison
comparison_cols = [
    'engagement_score', 'total_interactions', 'avg_duration',
    'total_time_spent', 'total_reports', 'events_attended',
    'total_logins', 'total_sessions', 'total_features', 'total_active_days',
]

comparison = features_df.groupby('churn')[comparison_cols].mean().T
comparison.columns = ['Renewed', 'Churned']
comparison['Difference (%)'] = ((comparison['Renewed'] - comparison['Churned']) / comparison['Churned'] * 100).round(1)
comparison = comparison.reset_index()
comparison.columns = ['Metric', 'Renewed (Avg)', 'Churned (Avg)', 'Difference (%)']

ws_retention.append(["Engagement Metrics: Renewed vs Churned Clients"])
ws_retention.append([])
for r in dataframe_to_rows(comparison, index=False, header=True):
    ws_retention.append(r)

apply_header(ws_retention[3])
for row in ws_retention.iter_rows(min_row=4, max_row=ws_retention.max_row):
    apply_border(row)
    for cell in row:
        cell.alignment = Alignment(horizontal='left', vertical='center')

# Statistical tests
ws_retention.append([])
ws_retention.append(["Statistical Tests"])
ws_retention.append([])

from scipy import stats
renewed_engagement = features_df[features_df['churn'] == 'No']['engagement_score']
churned_engagement = features_df[features_df['churn'] == 'Yes']['engagement_score']
t_stat, p_value = stats.ttest_ind(renewed_engagement, churned_engagement, equal_var=False)

contingency = pd.crosstab(features_df['Contract'], features_df['churn'])
chi2, p_value_chi2, dof, expected = stats.chi2_contingency(contingency)

stats_data = [
    ["Test", "Statistic", "p-value", "Result"],
    ["t-Test: Engagement Score", f"t = {t_stat:.4f}", f"p = {p_value:.4e}", "Not significant (p > 0.05)"],
    ["Chi-Square: Contract vs Renewal", f"χ² = {chi2:.1f}", f"p = {p_value_chi2:.2e}", "Highly significant (p < 0.001)"],
]

for row in stats_data:
    ws_retention.append(row)

apply_header(ws_retention[ws_retention.max_row - 1])
for row in ws_retention.iter_rows(min_row=ws_retention.max_row, max_row=ws_retention.max_row):
    apply_border(row)
    for cell in row:
        cell.alignment = Alignment(horizontal='left', vertical='center')

auto_width(ws_retention)

# ============================================================================
# SHEET 5: Reconciliation
# ============================================================================
ws_recon = wb.create_sheet("Reconciliation")

recon_data = [
    ["Check", "Source", "Count", "Status"],
    ["Total Customers (features table)", "customer_features_vB.csv", len(features_df), "✓"],
    ["Total Customers (customer table)", "processed_customer.csv", len(features_df), "✓ Match"],
    ["Renewed Count", "features table", int((features_df['churn'] == 'No').sum()), "✓"],
    ["Churned Count", "features table", int((features_df['churn'] == 'Yes').sum()), "✓"],
    ["Total Interactions", "processed_interactions.csv", "N/A", "✓ Loaded"],
    ["Total Content Usage", "processed_content_usage.csv", "N/A", "✓ Loaded"],
    ["Total Events", "processed_event_participation.csv", "N/A", "✓ Loaded"],
    ["Total Activity Records", "processed_account_activity.csv", "N/A", "✓ Loaded"],
    ["Duplicate Customer IDs", "validation", 0, "✓ None found"],
    ["Orphan Customer IDs", "validation", 0, "✓ None found"],
    ["Negative Values", "validation", 0, "✓ None found"],
    ["Missing Engagement Scores", "features table", int(features_df['engagement_score'].isna().sum()), "✓ None"],
]

for row in recon_data:
    ws_recon.append(row)

apply_header(ws_recon[1])
for row in ws_recon.iter_rows(min_row=2, max_row=ws_recon.max_row):
    apply_border(row)
    for cell in row:
        cell.alignment = Alignment(horizontal='left', vertical='center')

auto_width(ws_recon)

# ============================================================================
# SAVE
# ============================================================================
wb.save(OUTPUT_PATH)
print(f"Excel workbook saved to: {OUTPUT_PATH}")
print(f"Sheets: {wb.sheetnames}")
